# Generated by Django 6.0.2 on 2026-02-13 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('ra', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='RA')),
                ('nome_aluno', models.CharField(max_length=100, verbose_name='Nome do Aluno')),
                ('data_nasc', models.DateField(verbose_name='Data de Nascimento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Gênero')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('cod_cur', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cur', models.CharField(max_length=100, verbose_name='Nome do Curso')),
                ('carga_horaria_cur', models.IntegerField(verbose_name='Carga Horária')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('rp', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='RP')),
                ('nome_prof', models.CharField(max_length=100, verbose_name='Nome do Professor')),
                ('data_nasc', models.DateField(verbose_name='Data de Nascimento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Gênero')),
                ('titulacao', models.CharField(max_length=50, verbose_name='Titulação')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('cod_mat', models.AutoField(primary_key=True, serialize=False)),
                ('data_mat', models.DateField(auto_now_add=True, verbose_name='Data da Matrícula')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='escola.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='escola.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('cod_disc', models.AutoField(primary_key=True, serialize=False)),
                ('nome_disc', models.CharField(max_length=100, verbose_name='Nome da Disciplina')),
                ('carga_horaria_disc', models.IntegerField(verbose_name='Carga Horária')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='escola.curso')),
                ('professores', models.ManyToManyField(related_name='disciplinas', to='escola.professor')),
            ],
        ),
    ]
